version: '3'

services:
  checkbox_test:
    image: checkbox_test:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\user\source\repos\Checkbox_test\Checkbox_test:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

